# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distributed_printing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'distributed_printing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64istributed_printing.proto\x12\x14\x64istributed_printing\"m\n\x0cPrintRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x17\n\x0fmessage_content\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\x12\x16\n\x0erequest_number\x18\x04 \x01(\x05\"Y\n\rPrintResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14\x63onfirmation_message\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"U\n\rAccessRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\"8\n\x0e\x41\x63\x63\x65ssResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\"U\n\rAccessRelease\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\"A\n\x0cReplyMessage\x12\x16\n\x0e\x66rom_client_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\"\x0f\n\rEmptyResponse2k\n\x0fPrintingService\x12X\n\rSendToPrinter\x12\".distributed_printing.PrintRequest\x1a#.distributed_printing.PrintResponse2\xa5\x02\n\x16MutualExclusionService\x12Z\n\rRequestAccess\x12#.distributed_printing.AccessRequest\x1a$.distributed_printing.AccessResponse\x12T\n\tSendReply\x12\".distributed_printing.ReplyMessage\x1a#.distributed_printing.EmptyResponse\x12Y\n\rReleaseAccess\x12#.distributed_printing.AccessRelease\x1a#.distributed_printing.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_printing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRINTREQUEST']._serialized_start=52
  _globals['_PRINTREQUEST']._serialized_end=161
  _globals['_PRINTRESPONSE']._serialized_start=163
  _globals['_PRINTRESPONSE']._serialized_end=252
  _globals['_ACCESSREQUEST']._serialized_start=254
  _globals['_ACCESSREQUEST']._serialized_end=339
  _globals['_ACCESSRESPONSE']._serialized_start=341
  _globals['_ACCESSRESPONSE']._serialized_end=397
  _globals['_ACCESSRELEASE']._serialized_start=399
  _globals['_ACCESSRELEASE']._serialized_end=484
  _globals['_REPLYMESSAGE']._serialized_start=486
  _globals['_REPLYMESSAGE']._serialized_end=551
  _globals['_EMPTYRESPONSE']._serialized_start=553
  _globals['_EMPTYRESPONSE']._serialized_end=568
  _globals['_PRINTINGSERVICE']._serialized_start=570
  _globals['_PRINTINGSERVICE']._serialized_end=677
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_start=680
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
