# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distributed_printing_pb2 as distributed__printing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distributed_printing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrintingServiceStub(object):
    """Serviço do servidor burro de impressão
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendToPrinter = channel.unary_unary(
                '/distributed_printing.PrintingService/SendToPrinter',
                request_serializer=distributed__printing__pb2.PrintRequest.SerializeToString,
                response_deserializer=distributed__printing__pb2.PrintResponse.FromString,
                _registered_method=True)


class PrintingServiceServicer(object):
    """Serviço do servidor burro de impressão
    """

    def SendToPrinter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrintingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendToPrinter': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToPrinter,
                    request_deserializer=distributed__printing__pb2.PrintRequest.FromString,
                    response_serializer=distributed__printing__pb2.PrintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_printing.PrintingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_printing.PrintingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrintingService(object):
    """Serviço do servidor burro de impressão
    """

    @staticmethod
    def SendToPrinter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_printing.PrintingService/SendToPrinter',
            distributed__printing__pb2.PrintRequest.SerializeToString,
            distributed__printing__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutualExclusionServiceStub(object):
    """Serviço para comunicação entre clientes (Mutual Exclusion)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/distributed_printing.MutualExclusionService/RequestAccess',
                request_serializer=distributed__printing__pb2.AccessRequest.SerializeToString,
                response_deserializer=distributed__printing__pb2.AccessResponse.FromString,
                _registered_method=True)
        self.SendReply = channel.unary_unary(
                '/distributed_printing.MutualExclusionService/SendReply',
                request_serializer=distributed__printing__pb2.ReplyMessage.SerializeToString,
                response_deserializer=distributed__printing__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ReleaseAccess = channel.unary_unary(
                '/distributed_printing.MutualExclusionService/ReleaseAccess',
                request_serializer=distributed__printing__pb2.AccessRelease.SerializeToString,
                response_deserializer=distributed__printing__pb2.EmptyResponse.FromString,
                _registered_method=True)


class MutualExclusionServiceServicer(object):
    """Serviço para comunicação entre clientes (Mutual Exclusion)
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutualExclusionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=distributed__printing__pb2.AccessRequest.FromString,
                    response_serializer=distributed__printing__pb2.AccessResponse.SerializeToString,
            ),
            'SendReply': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReply,
                    request_deserializer=distributed__printing__pb2.ReplyMessage.FromString,
                    response_serializer=distributed__printing__pb2.EmptyResponse.SerializeToString,
            ),
            'ReleaseAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseAccess,
                    request_deserializer=distributed__printing__pb2.AccessRelease.FromString,
                    response_serializer=distributed__printing__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_printing.MutualExclusionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_printing.MutualExclusionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutualExclusionService(object):
    """Serviço para comunicação entre clientes (Mutual Exclusion)
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_printing.MutualExclusionService/RequestAccess',
            distributed__printing__pb2.AccessRequest.SerializeToString,
            distributed__printing__pb2.AccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_printing.MutualExclusionService/SendReply',
            distributed__printing__pb2.ReplyMessage.SerializeToString,
            distributed__printing__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_printing.MutualExclusionService/ReleaseAccess',
            distributed__printing__pb2.AccessRelease.SerializeToString,
            distributed__printing__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
